#!/usr/bin/env python3
"""Generate docs/evidence.html from the JSON receipts, so the site cannot drift from the data."""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path("/home/user/GEMSDOE46")
D = ROOT / "data"
meas = json.loads((D / "measurements.json").read_text())
em = json.loads((D / "emission_model.json").read_text())
inv = json.loads((D / "truth_inversion.json").read_text())
ver = json.loads((D / "verification.json").read_text())
cred = json.loads((D / "credit_model.json").read_text())

score_of = {m["anchor_id"]: m.get("reported_score") or "" for m in meas}
loo = dict(zip(em["anchors"], em["loo_pred"]))
N = dict(zip(em["anchors"], em["N"]))
mS = dict(zip(em["anchors"], em["mean_S"]))
dc = dict(zip(em["anchors"], em["dcat_med"]))

rows = []
for m in sorted(meas, key=lambda r: -float(r.get("reported_score") or 0)):
    aid = m["anchor_id"]
    if not score_of.get(aid):
        continue
    rows.append(
        f"<tr><td>{aid}</td><td>{m['reported_score']}</td>"
        f"<td>{m.get('dots', 0):,}</td><td>{m.get('on_catalogue_dots', 0):,}</td>"
        f"<td>{m.get('median_dist_to_catalogue_px', '')}</td>"
        f"<td>{N.get(aid, 0):,}</td><td>{mS.get(aid, 0):.3f}</td>"
        f"<td>{dc.get(aid, 0):.1f}</td><td>{loo.get(aid, float('nan')):.3f}</td>"
        f"<td><code>{m['repo']}</code></td></tr>")

checks = "\n".join(
    f"<tr><td>{c['check']}</td><td><span class='{'pass' if c['ok'] else 'fail'}'>"
    f"{'PASS' if c['ok'] else 'FAIL'}</span></td><td><code>{c['detail']}</code></td></tr>"
    for c in ver["checks"])

uniq = "\n".join(
    f"<tr><td>{u['anchor']}</td><td>{u['jaccard']:.4f}</td><td>{u['shared']:,}</td>"
    f"<td>{u['anchor_dots']:,}</td></tr>" for u in ver["uniqueness_top5"])

stage_a = "\n".join(
    f"<tr><td>#{i + 1}</td><td><code>{cred['stage_a']['names'][k]}</code></td>"
    f"<td>{cred['stage_a']['beta_standardised'][k]:+.4f}</td></tr>"
    for i, k in enumerate(cred["stage_a"]["keep"][:12]))

html = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Evidence and receipts | GEMS46</title><link rel="stylesheet" href="style.css"></head>
<body>
<header class="site"><div class="wrap">
  <a class="brand" href="index.html">GEMS46 · DOE GEMS Prize</a>
  <nav><a href="index.html">Home</a><a href="submit.html">How to submit</a>
  <a href="method.html">Method</a><a href="hypotheses.html">Hypotheses</a>
  <a href="evidence.html" aria-current="page">Evidence</a><a href="sources.html">Sources</a></nav>
</div></header>
<main class="wrap">
<h1>Evidence and receipts</h1>
<p class="lede">Every number quoted anywhere on this site is generated by a script in the
repository from a public artefact, and every table below is rendered directly from those JSON
receipts by <code>scripts/build_evidence_page.py</code>. Nothing is typed by hand.</p>

<h2>1. Submission contract — {len(ver['checks']) - ver['failures']}/{len(ver['checks'])} checks pass</h2>
<p>SHA-256 <code>{ver['sha256']}</code> · {ver['bytes']:,} bytes · {ver['nonzero']:,} non-zero cells.</p>
<table><tr><th>Check</th><th>Result</th><th>Detail</th></tr>
{checks}</table>

<h2>2. Uniqueness — overlap with the closest prior submissions</h2>
<p>Jaccard overlap of the emitted dot set with every one of the 43 locally available scored
rasters. Maximum: <strong>{ver['uniqueness_top5'][0]['jaccard']:.4f}</strong>
(vs <code>{ver['uniqueness_top5'][0]['anchor']}</code>). The submission shares
{ver['uniqueness_top5'][0]['shared']:,} pixels with it out of
{ver['uniqueness_top5'][0]['anchor_dots']:,} emitted by that file.</p>
<table><tr><th>Anchor</th><th>Jaccard</th><th>Shared px</th><th>Anchor dots</th></tr>
{uniq}</table>

<h2>3. The anchor ledger (score → geometry → model)</h2>
<p><code>median d(cat)</code> is the median distance of an emitted dot to the given catalogue, in
100 m pixels. <code>LOO</code> is the leave-one-anchor-out prediction of the size-aware model,
where every anchor whose raster correlates above 0.9 with the held-out file is removed from the
training fold — so duplicate re-emissions cannot leak.</p>
<table>
<tr><th>Anchor</th><th>Reported</th><th>Dots</th><th>On catalogue</th><th>median d(cat)</th>
<th>N</th><th>mean S</th><th>d(cat) med</th><th>LOO pred</th><th>Source repo</th></tr>
{''.join(rows)}
</table>

<h2>4. Model coefficients</h2>
<p>Stage A ridge on coverage-weighted feature means; the twelve largest standardised
coefficients of the {len(cred['stage_a']['names'])}-feature fit (LOO Spearman
{cred['stage_a']['loo_spearman']:+.3f}, RMSE {cred['stage_a']['loo_rmse']:.4f}).</p>
<table><tr><th>#</th><th>Feature</th><th>Standardised coefficient</th></tr>
{stage_a}</table>
<p>Stage B size-aware model on <code>[mean_S, log N, median distance to catalogue]</code>:
LOO Spearman <strong>{em['loo_spearman']:+.3f}</strong>, RMSE <strong>{em['loo_rmse']:.4f}</strong>
on {len(em['anchors'])} anchors.</p>

<h2>5. The negative result, with its receipts</h2>
<table>
<tr><th>Quantity</th><th>Value</th></tr>
<tr><td>Truth-field inversion, in-sample Pearson</td><td>{inv['in_sample']['pearson']:+.3f}</td></tr>
<tr><td>Truth-field inversion, in-sample RMSE</td><td>{inv['in_sample']['rmse']:.4f}</td></tr>
<tr><td>Truth-field inversion, de-duplicated LOO Pearson</td>
    <td><span class="fail">{inv['loo']['pearson']:+.3f}</span></td></tr>
<tr><td>De-duplicated LOO RMSE</td><td>{inv['loo']['rmse']:.4f}</td></tr>
<tr><td>Fitted hidden-truth size |G|</td><td>{inv['n_truth']:,.0f} px (community estimate ≈ 7,900 px)</td></tr>
</table>
<p>Interpretation: the public record pins down the <em>size</em> of the hidden truth set but not
its <em>arrangement</em>. A model that fits the 43 equations to Pearson +0.89 and then loses
everything out-of-sample is fitting the ensemble, not the physics. Published here so that no
future run spends a weekly submission slot on a locally "validated" absolute score.</p>

<h2>6. Reproduce every row</h2>
<pre><code>python3 -m venv /tmp/venv &amp;&amp; /tmp/venv/bin/pip install numpy scipy tifffile imagecodecs \\
    rasterio scikit-image pandas matplotlib pytest
/tmp/venv/bin/python scripts/fetch_data.py            # 49 scored rasters + grid rasters
/tmp/venv/bin/python scripts/measure_anchors.py       # section 3 geometry columns
/tmp/venv/bin/python scripts/build_credit_model.py    # section 4 stage A
/tmp/venv/bin/python scripts/build_credit_map.py      # credit direction r(x)
/tmp/venv/bin/python scripts/emission_search.py       # section 4 stage B
/tmp/venv/bin/python scripts/build_submission.py --n-dots 37654 --tag ridge
/tmp/venv/bin/python scripts/verify_submission.py     # sections 1 and 2
/tmp/venv/bin/python scripts/invert_blocks.py         # section 5
/tmp/venv/bin/python scripts/build_evidence_page.py   # regenerates this page
</code></pre>
</main>
<footer class="site"><div class="wrap">GEMS46 · receipts regenerated from the JSON in
<code>data/</code> · <a href="sources.html">Sources →</a></div></footer>
</body></html>
"""
(ROOT / "docs" / "evidence.html").write_text(html)
print(f"wrote docs/evidence.html ({len(html):,} bytes, {len(rows)} ledger rows)")
